name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      INSTALL_DIR: "/tmp/binutils"

    steps:
      - uses: actions/checkout@v3
   
      - name: Setup build environment
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential libgmp-dev libmpfr-dev

      - name: Configure
        run: |
          mkdir $INSTALL_DIR
          mkdir build
          cd build
          ../configure \
              --disable-werror \
              --with-mmap \
              --prefix=$INSTALL_DIR

      - name: Build
        run: |
          cd build
          make
          make install
   
      - name: Package
        run: |
            tar -czvf omftools-linux-x86_64.tar.gz --transform='s|nm|omf-nm|' --transform='s|objdump|omf-objdump|' -C $INSTALL_DIR/bin nm objdump
            tar -czvf binutils-linux-x86_64.tar.gz -C $INSTALL_DIR bin include lib share
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: binutils-linux-x86_64.tar.gz
            path: ./binutils-linux-x86_64.tar.gz
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: omftools-linux-x86_64.tar.gz
            path: ./omftools-linux-x86_64.tar.gz

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: omftools-linux-x86_64.tar.gz