name: Binutils-gdb build and release

on:
  push:
    tags:
      - '*.*.*' # Triggers the workflow on version tags, e.g., 1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INSTALL_DIR: "/tmp/binutils"

    steps:
    - uses: actions/checkout@v4

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libgmp-dev libmpfr-dev
    - name: Extract tag name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Configure
      run: |
       mkdir $INSTALL_DIR
       mkdir build
       cd build
       ../configure \
          --disable-werror \
          --with-mmap

    - name: Build
      run: |
       cd build
       make
